Repository kakaobrain/trident, pull requests merged in 2023-09, with the labels that each got.

#87 Support for printing modules
  trident/module.py
Labels: enhancement

#32 Optimize GroupNorm
  benchmarks/benchmark_group_norm.py
  tests/test_group_norm.py
  trident/function/function.py
  trident/kernel/group_norm.py
  trident/operation/group_norm.py
Labels: enhancement

#88 Refactor SiLU
  benchmarks/benchmark_silu.py
  tests/test_silu.py
  trident/function/function.py
  trident/kernel/silu.py
  trident/module.py
  trident/operation/silu.py
Labels: enhancement

#89 Fix a bug in Dropout
  benchmarks/benchmark_dropout.py
  benchmarks/benchmark_silu.py
  tests/test_dropout.py
  trident/function/function.py
  trident/kernel/dropout.py
  trident/module.py
  trident/operation/dropout.py
  trident/operation/silu.py
Labels: bug

#91 Support for batching in Linear
  tests/test_linear.py
  trident/function/function.py
  trident/kernel/linear.py
  trident/operation/linear.py
Labels: enhancement

#92 Add LayerNorm tests
  tests/test_layer_norm.py
  trident/kernel/layer_norm.py
Labels: bug, enhancement

#93 Refactor argmax function
  benchmarks/benchmark_argmax.py
  benchmarks/benchmark_gelu.py
  tests/test_argmax.py
  trident/function/function.py
  trident/kernel/argmax.py
  trident/kernel/gelu.py
  trident/module.py
  trident/operation/argmax.py
  trident/operation/gelu.py
  trident/util/util.py
Labels: enhancement

#97 Enable using accelerator when creating modules
  trident/module.py
Labels: enhancement

#95 Refactor Max
  tests/test_linear.py
  tests/test_max.py
  trident/function/function.py
  trident/kernel/max.py
  trident/language/function.py
  trident/module.py
  trident/operation/max.py
Labels: enhancement

#101 Fix bugs in GEGLU
  benchmarks/benchmark_geglu.py
  tests/test_geglu.py
  trident/kernel/geglu.py
  trident/language/math/gelu.py
  trident/operation/geglu.py
Labels: bug

#102 Refactor InstanceNorm
  tests/test_instance_norm.py
  trident/function/function.py
  trident/kernel/instance_norm.py
  trident/module.py
  trident/operation/instance_norm.py
  trident/util/util.py
Labels: enhancement

#104 Use autotune in CosineSimilarity
  tests/test_cosine_similarity.py
  trident/function/function.py
  trident/kernel/cosine_similarity.py
  trident/operation/cosine_similarity.py
  trident/util/util.py
Labels: enhancement

#106 Update install_package.sh
  install_package.sh
Labels: bug

#111 Refactor CosineSimiliarity
  benchmarks/benchmark_cosine_similarity.py
  tests/test_cosine_similarity.py
  trident/kernel/cosine_similarity.py
  trident/operation/cosine_similarity.py
  trident/util/util.py
Labels: enhancement

#113 Fix overflow in GroupNorm
  trident/kernel/group_norm.py
Labels: bug

#112 Refactor Softmax
  benchmarks/benchmark_softmax.py
  tests/test_softmax.py
  trident/function/function.py
  trident/kernel/softmax.py
  trident/language/combine.py
  trident/module.py
  trident/operation/attention.py
  trident/operation/cosine_similarity.py
  trident/operation/dropout.py
  trident/operation/geglu.py
  trident/operation/gelu.py
  trident/operation/group_norm.py
  trident/operation/instance_norm.py
  trident/operation/layer_norm.py
  trident/operation/leaky_relu.py
  trident/operation/linear.py
  trident/operation/max.py
  trident/operation/mean.py
  trident/operation/prelu.py
  trident/operation/relu.py
  trident/operation/rms_norm.py
  trident/operation/silu.py
  trident/operation/softmax.py
  trident/operation/sum.py
  trident/operation/var.py
  trident/operation/var_mean.py
Labels: enhancement

#114 Fix bugs in PReLU
  benchmarks/benchmark_prelu.py
  tests/test_prelu.py
  trident/function/function.py
  trident/kernel/mean.py
  trident/kernel/prelu.py
  trident/kernel/shift_gelu.py
  trident/kernel/var.py
  trident/kernel/var_mean.py
  trident/operation/prelu.py
Labels: bug

#115 Update .pre-commit-config.yaml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
Labels: enhancement

#116 Fix GEGLU test failures
  tests/test_geglu.py
  tests/util.py
Labels: bug

#118 Deprecate AdaptiveAvgPool2d, Conv2d and MaxPool2d
  benchmarks/benchmark_adaptive_avg_pool2d.py
  benchmarks/benchmark_conv2d.py
  benchmarks/benchmark_max_pool2d.py
  benchmarks/benchmarker.py
  tests/test_adaptive_avg_pool2d.py
  tests/test_conv2d.py
  tests/test_max_pool2d.py
  trident/function/function.py
  trident/kernel/__init__.py
  trident/kernel/adaptive_avg_pool2d.py
  trident/kernel/batch_norm.py
  trident/kernel/conv2d.py
  trident/kernel/cosine_similarity.py
  trident/kernel/max_pool2d.py
  trident/language/__init__.py
  trident/language/function.py
  trident/module.py
  trident/operation/__init__.py
  trident/operation/adaptive_avg_pool2d.py
  trident/operation/conv2d.py
  trident/operation/max_pool2d.py
Labels: enhancement

#119 Refactor benchmarks
  benchmarks/benchmark_argmax.py
  benchmarks/benchmark_attention.py
  benchmarks/benchmark_batch_norm.py
  benchmarks/benchmark_cosine_similarity.py
  benchmarks/benchmark_dropout.py
  benchmarks/benchmark_geglu.py
  benchmarks/benchmark_gelu.py
  benchmarks/benchmark_instance_norm.py
  benchmarks/benchmark_layer_norm.py
  benchmarks/benchmark_leaky_relu.py
  benchmarks/benchmark_max.py
  benchmarks/benchmark_mean.py
  benchmarks/benchmark_prelu.py
  benchmarks/benchmark_relu.py
  benchmarks/benchmark_rms_norm.py
  benchmarks/benchmark_shift_gelu.py
  benchmarks/benchmark_silu.py
  benchmarks/benchmark_softmax.py
  benchmarks/benchmark_sum.py
  benchmarks/benchmark_var.py
  benchmarks/benchmark_var_mean.py
  tests/test_max.py
  tests/test_mean.py
  tests/test_sum.py
  tests/test_var.py
  tests/test_var_mean.py
  trident/operation/instance_norm.py
Labels: enhancement

#122 Fix overflow in InstanceNorm, LayerNorm and RMSNorm
  trident/kernel/instance_norm.py
  trident/kernel/layer_norm.py
  trident/kernel/rms_norm.py
Labels: enhancement

#121 Add trace to config
  examples/playground.py
  requirements.txt
  trident/config.py
  trident/kernel/sum.py
  trident/operation/argmax.py
  trident/operation/attention.py
  trident/operation/batch_norm.py
  trident/operation/cosine_similarity.py
  trident/operation/dropout.py
  trident/operation/geglu.py
  trident/operation/gelu.py
  trident/operation/group_norm.py
  trident/operation/instance_norm.py
  trident/operation/layer_norm.py
  trident/operation/leaky_relu.py
  trident/operation/linear.py
  trident/operation/max.py
  trident/operation/mean.py
  trident/operation/prelu.py
  trident/operation/relu.py
  trident/operation/rms_norm.py
  trident/operation/shift_gelu.py
  trident/operation/silu.py
  trident/operation/softmax.py
  trident/operation/sum.py
  trident/operation/var.py
  trident/operation/var_mean.py
  trident/util/util.py
Labels: enhancement

#125 Fix a bug in InstanceNorm not using input status
  tests/test_instance_norm.py
  trident/kernel/instance_norm.py
  trident/operation/instance_norm.py
Labels: bug

#126 Add dropout feature to Attention
  benchmarks/benchmark_attention.py
  tests/test_attention.py
  trident/function/function.py
  trident/kernel/attention.py
  trident/kernel/dropout.py
  trident/kernel/softmax.py
  trident/language/constant.py
  trident/operation/attention.py
Labels: enhancement

#133 Release Trident 1.0.0
  setup.py
Labels: enhancement

#136 Remove dead code
  tests/test_geglu.py
Labels: enhancement

#138 Release Trident 1.0.1
  setup.py
Labels: enhancement

#140 Optimize Softmax
  trident/kernel/softmax.py
Labels: enhancement

#142 Optimize RMSNorm
  trident/kernel/rms_norm.py
Labels: enhancement

#143 Fix a bug in argmax function
  trident/kernel/argmax.py
Labels: bug

#145 Optimize Sum
  tests/test_sum.py
  trident/function/function.py
  trident/kernel/sum.py
  trident/language/constant.py
  trident/language/mean.py
  trident/language/sum.py
Labels: enhancement

#144 Optimize PReLU
  trident/kernel/prelu.py
Labels: enhancement

#146 Optimize GroupNorm
  benchmarks/benchmark_group_norm.py
  trident/kernel/group_norm.py
  trident/operation/group_norm.py
Labels: enhancement

#147 Optimize VarMean
  trident/function/function.py
  trident/kernel/var.py
  trident/kernel/var_mean.py
  trident/language/var_mean.py
  trident/operation/var_mean.py
Labels: enhancement

#148 Optimize Var
  trident/function/function.py
  trident/kernel/mean.py
  trident/kernel/var.py
  trident/kernel/var_mean.py
  trident/language/mean.py
  trident/language/var.py
  trident/operation/var.py
Labels: enhancement

#149 Optimize Mean
  trident/function/function.py
  trident/kernel/mean.py
  trident/operation/mean.py
Labels: enhancement

#150 Optimize SiLU
  trident/function/function.py
  trident/kernel/silu.py
  trident/operation/silu.py
Labels: enhancement

#151 Release Trident 1.0.2
  setup.py
Labels: enhancement
