Repository kakaobrain/trident, pull requests merged in 2023-10, with the labels that each got.

#155 Optimize Dropout
  trident/kernel/dropout.py
Labels: enhancement

#156 Add attribute for version checking
  trident/__init__.py
Labels: enhancement

#158 Support bias in Attention
  tests/test_attention.py
  trident/function/function.py
  trident/kernel/attention.py
  trident/operation/attention.py
Labels: enhancement

#160 Update README.md
  README.md
Labels: documentation

#163 Use power of 2 size tensors in Attention benchmark
  benchmarks/benchmark_attention.py
  trident/operation/attention.py
  trident/util/util.py
Labels: bug

#164 Release Trident 1.1.0
  setup.py
  trident/__init__.py
Labels: enhancement
