Repository kakaobrain/trident, pull requests merged in 2023-07, with the labels that each got.

#15 Optimize Softmax
  tests/test_softmax.py
  trident/kernel/softmax.py
  trident/language/language.py
  trident/math/math.py
  trident/operation/softmax.py
Labels: enhancement

#16 Disallow tf32 conversion in Linear
  tests/test_linear.py
  trident/kernel/linear.py
Labels: bug

#17 Implement LayerNorm
  benchmarks/benchmark_layer_norm.py
  benchmarks/benchmarker.py
  tests/test_layer_norm.py
  trident/function/function.py
  trident/kernel/__init__.py
  trident/kernel/layer_norm.py
  trident/kernel/softmax.py
  trident/language/language.py
  trident/module.py
  trident/operation/__init__.py
  trident/operation/layer_norm.py
Labels: enhancement

#20 Implement GELU
  benchmarks/benchmark_gelu.py
  benchmarks/benchmarker.py
  tests/test_gelu.py
  trident/function/function.py
  trident/kernel/__init__.py
  trident/kernel/gelu.py
  trident/language/language.py
  trident/module.py
  trident/operation/__init__.py
  trident/operation/gelu.py
  trident/util/util.py
Labels: enhancement

#21 Optimize to get shared memory size per block
  requirements.txt
  trident/operation/gelu.py
  trident/operation/instance_norm.py
  trident/util/util.py
Labels: enhancement

#22 Optimize LayerNorm
  benchmarks/benchmark_layer_norm.py
  trident/kernel/layer_norm.py
  trident/kernel/softmax.py
  trident/operation/gelu.py
  trident/operation/instance_norm.py
  trident/operation/layer_norm.py
  trident/operation/softmax.py
  trident/util/util.py
Labels: enhancement

#23 Refactor benchmarks
  benchmarks/benchmark_adaptive_avg_pool2d.py
  benchmarks/benchmark_conv2d.py
  benchmarks/benchmark_dropout.py
  benchmarks/benchmark_gelu.py
  benchmarks/benchmark_instance_norm.py
  benchmarks/benchmark_layer_norm.py
  benchmarks/benchmark_leaky_relu.py
  benchmarks/benchmark_linear.py
  benchmarks/benchmark_max_pool2d.py
  benchmarks/benchmark_prelu.py
  benchmarks/benchmark_relu.py
  benchmarks/benchmark_silu.py
  benchmarks/benchmark_softmax.py
  benchmarks/benchmarker.py
  benchmarks/util.py
Labels: enhancement

#24 Optimize Softmax
  benchmarks/benchmark_softmax.py
  tests/test_softmax.py
  trident/kernel/math.py
  trident/kernel/softmax.py
  trident/language/language.py
  trident/operation/softmax.py
Labels: enhancement

#25 Optimize memory usage of LayerNorm
  tests/test_layer_norm.py
  trident/function/function.py
  trident/kernel/instance_norm.py
  trident/kernel/layer_norm.py
  trident/kernel/math.py
  trident/module.py
  trident/operation/gelu.py
  trident/operation/instance_norm.py
  trident/operation/layer_norm.py
  trident/operation/softmax.py
  trident/util/util.py
Labels: enhancement

#18 Implement BatchNorm1d
  benchmarks/benchmark_batch_norm.py
  benchmarks/benchmarker.py
  tests/test_batch_norm.py
  trident/function/function.py
  trident/kernel/__init__.py
  trident/kernel/batch_norm.py
  trident/module.py
  trident/operation/__init__.py
  trident/operation/batch_norm.py
Labels: enhancement

#26 Reformat code
  .github/workflows/tests.yml
  benchmarks/benchmark_adaptive_avg_pool2d.py
  benchmarks/benchmark_batch_norm.py
  benchmarks/benchmark_conv2d.py
  benchmarks/benchmark_dropout.py
  benchmarks/benchmark_gelu.py
  benchmarks/benchmark_instance_norm.py
  benchmarks/benchmark_layer_norm.py
  benchmarks/benchmark_leaky_relu.py
  benchmarks/benchmark_linear.py
  benchmarks/benchmark_max_pool2d.py
  benchmarks/benchmark_prelu.py
  benchmarks/benchmark_relu.py
  benchmarks/benchmark_silu.py
  benchmarks/benchmark_softmax.py
  benchmarks/benchmarker.py
  benchmarks/util.py
  setup.py
  tests/conftest.py
  tests/test_adaptive_avg_pool2d.py
  tests/test_batch_norm.py
  tests/test_conv2d.py
  tests/test_dropout.py
  tests/test_gelu.py
  tests/test_instance_norm.py
  tests/test_layer_norm.py
  tests/test_leaky_relu.py
  tests/test_linear.py
  tests/test_max_pool2d.py
  tests/test_prelu.py
  tests/util.py
  trident/function/function.py
  trident/kernel/adaptive_avg_pool2d.py
  trident/kernel/batch_norm.py
  trident/kernel/conv2d.py
  trident/kernel/dropout.py
  trident/kernel/instance_norm.py
  trident/kernel/layer_norm.py
  trident/kernel/leaky_relu.py
  trident/kernel/linear.py
  trident/kernel/max_pool2d.py
  trident/kernel/prelu.py
  trident/kernel/relu.py
  trident/kernel/silu.py
  trident/kernel/softmax.py
  trident/module.py
  trident/operation/adaptive_avg_pool2d.py
  trident/operation/batch_norm.py
  trident/operation/conv2d.py
  trident/operation/dropout.py
  trident/operation/gelu.py
  trident/operation/instance_norm.py
  trident/operation/layer_norm.py
  trident/operation/leaky_relu.py
  trident/operation/linear.py
  trident/operation/max_pool2d.py
  trident/operation/prelu.py
  trident/operation/relu.py
  trident/operation/silu.py
Labels: enhancement

#28 Optimize Linear
  benchmarks/benchmark_adaptive_avg_pool2d.py
  benchmarks/benchmark_batch_norm.py
  benchmarks/benchmark_conv2d.py
  benchmarks/benchmark_dropout.py
  benchmarks/benchmark_gelu.py
  benchmarks/benchmark_instance_norm.py
  benchmarks/benchmark_layer_norm.py
  benchmarks/benchmark_leaky_relu.py
  benchmarks/benchmark_linear.py
  benchmarks/benchmark_max_pool2d.py
  benchmarks/benchmark_prelu.py
  benchmarks/benchmark_relu.py
  benchmarks/benchmark_silu.py
  benchmarks/benchmark_softmax.py
  benchmarks/util.py
  tests/test_linear.py
  tests/util.py
  trident/kernel/linear.py
  trident/module.py
  trident/operation/linear.py
Labels: enhancement

#29 Implement InstanceNorm
  tests/test_instance_norm.py
  tests/test_softmax.py
  tests/util.py
  trident/function/function.py
  trident/kernel/instance_norm.py
  trident/kernel/layer_norm.py
  trident/kernel/math.py
  trident/kernel/softmax.py
  trident/language/language.py
  trident/module.py
  trident/operation/gelu.py
  trident/operation/instance_norm.py
  trident/operation/layer_norm.py
  trident/operation/softmax.py
  trident/util/util.py
Labels: enhancement

#31 Optimize InstanceNorm
  tests/test_kernel.py
  trident/__init__.py
  trident/kernel/instance_norm.py
  trident/kernel/math.py
  trident/language/language.py
  trident/operation/instance_norm.py
Labels: enhancement

#33 Implement tutorial example
  .pre-commit-config.yaml
  examples/tutorial.ipynb
Labels: enhancement

#34 Optimize Linear
  trident/kernel/linear.py
  trident/operation/linear.py
Labels: enhancement

#37 Implement optimize model function
  examples/tutorial.ipynb
  trident/operation/group_norm.py
  trident/operation/instance_norm.py
  trident/operation/layer_norm.py
  trident/operation/linear.py
  trident/util/util.py
Labels: enhancement

#38 Fix a bug in sum function
  tests/test_instance_norm.py
  tests/test_kernel.py
  tests/test_math.py
  trident/kernel/math.py
  trident/language/language.py
  trident/operation/instance_norm.py
Labels: bug, enhancement
